### ISSUE TITLE
Figure out balance between pages.18f.gov and 18f.github.io

### ISSUE THREAD

**Issue by gbinal** [18F/pages#1]
Not sure where best to discuss this but thinking through our use of `pages.18f.gov` in lieu of `18f.github.io` with @mbland right now.  

Some questions:  
1) Are we cool with migrating our current `18f.github.io/x` microsites over to `pages.18f.gov/x`? 
2) Should that be the new norm and should we deprecate our use of `18f.github.io/x`?    If not, what are our guidelines for when someone should use `pages.18f.gov` instead.  
3) Can/should we put up redirects from the `18f.github.io/x` microsites over to `pages.18f.gov/x` ones?  Or do we just phase in a new behavior and refer to the new urls from now on.   
4) Do we want to stick with that URL?  I also kind of like `labs.18f.gov`.  What do folks think?  

Are there other major questions we should think through?  

cc: @blacktm, @NoahKunin, @konklone, @leahbannon, @gboone,  @elainekamlley

**Comment by adelevie** [comment]
One thing that I've always liked with `x.github.io` was the freedom to experiment and publish fairly unilaterally. [How] Would that process change under `pages.18f.gov/x`?

**Comment by mbland** [comment]
@adelevie Not much. Just need to configure the webhook and push an update.

**Comment by afeld** [comment]
I don't have strong feelings about GitHub vs. Cloud Foundry (though the latter is far more flexible w/ things like plugins), or the URLs. The one thing to note, though, is that separate "apps" under Cloud Foundry would have different domains by default, not different paths under a single domain. The latter would take some finagling.

**Comment by gbinal** [comment]
@adelevie, I'm talking with @mbland and @blacktm right now and we're all thinking that it makes sense that we still have `18f.github.io/x` for utterly easy, quick experimentation and then whenever it's something that you want to start talking about publicly, you should activate it on `pages.18f.gov` and point people to that url.

**Comment by gbinal** [comment]
In that scenario, the `18f.github.io/x` and `pages.18f.gov/x` exist simultaneously, but you'd only want to be pointing people to the `pages.18f.gov/x` one.

**Comment by adelevie** [comment]
@gbinal then that settles that :)

I've benefitted from the ability to conduct "utterly easy, quick experimentation" with Pages and I'm sure that's the case across 18F. During prototyping sessions, for example, it's always been great to give folks a permanent URL with zero overhead.

**Comment by gbinal** [comment]
Sorry, last point.  Just to confirm, the level of effort of activating a project on `pages.18f.gov` would be tiny and updates to it would happen automatically with each edit to the `gh-pages` branch.

**Comment by adelevie** [comment]
Is it just technical effort? Or do we have to talk to a person about deploying?

**Comment by mbland** [comment]
I'd say just go with it. When you're ready to launch publicly, however you care to define that, set up the webhook and go for it. We're only talking about Jekyll-based sites here.

(Though it did just strike me that we _can_ run plugins on `pages.18f.gov`.)

**Comment by gboone** [comment]
Based on my understanding of The Rules if there's any chance you'll ever give the github.io url to a member of the public you should start on pages.18f.gov.

> I've benefitted from the ability to conduct "utterly easy, quick experimentation" with Pages and I'm sure that's the case across 18F. During prototyping sessions, for example, it's always been great to give folks a permanent URL with zero overhead.

I think this is a perfect use case for pages.18f.gov.

**Comment by blacktm** [comment]
@adelevie Just have to add a webhook (see below).

![screen shot 2015-04-27 at 3 11 48 pm](https://cloud.githubusercontent.com/assets/887429/7355442/dfdea43e-ecef-11e4-9b3d-e5f7238cea24.png)

We now have both:
- http://18f.github.io/consulting/
- https://pages.18f.gov/consulting/

**Comment by gbinal** [comment]
@gboone - yeah, I think it's fine to start off directly with `pages.18f.gov` but if unsure, it's also okay to start with `18f.github.io` and then activate the webhook at the first sign of needing to share more publicly.

**Comment by ultrasaurus** [comment]
I'd like all projects to have a single URL, not both  18f.github.io and pages.18f.gov -- I think it will be very confusing for the public.  Why not just use a gov-pages branch instead of gh-pages, then people can publish to one or the other, but not both.

cc @dhcole seems related to Federalist :)

**Comment by konklone** [comment]
If it's literally as simple as adding a webhook, and it Just Works, that seems like a pretty swell idea with very little overhead as compared to the 18f.github.io route.

Starting with pages.18f.gov sounds like a good idea. If pages.18f.gov ever goes down or something breaks the webhook, 18f.github.io will always be around and a `git push` away.

**Comment by mbland** [comment]
@ultrasaurus The point of developing pages.18f.gov is because we learned that we _shouldn't_ be pointing the public to 18f.github.io for ATO-related reasons (which @NoahKunin went into during the end of last week's coffee chat). Consequently, we should only be publicizing pages.18f.gov URLs.

That said, I'm open to the idea of switching the mechanism to a differently-named branch, but am still on the fence about it.

**Comment by leahbannon** [comment]
I strongly advocate for redirects from 18f.github.io/x if we do migrate. Otherwise, I'm :-1:

**Comment by mbland** [comment]
@leahbannon What's your reasoning?

**Comment by blacktm** [comment]
Just to clarify, you first create a gh-pages repo, then would have the option of "promoting" it to "pages.18f.gov" for intentional public consumption.

**Comment by konklone** [comment]
Seems like we could solve this by just saying:

* Change the trigger branch for pages.18f.gov from `gh-pages` to `18f-pages`.
* Instruct everyone to just start with pages.18f.gov.
* If people really need to use 18f.github.io for some reason (pages.18f.gov is down, they have write permissions but not admin permissions to create the webhook, or some other existential thing) then push to `gh-pages` and go for it until you work out whatever's up. The level of use will end up being exceptional and temporary.

**Comment by leahbannon** [comment]
@mbland I may not have been very clear... I mean I support this as long as we offer a redirect so we're not breaking the old links. (Let me know if you still want more reasoning explanation.)

**Comment by gbinal** [comment]
@leahbannon - Sorry, it's my bad for not being clear.  The model I was espousing wouldn't kill the 18f.github.io pages.   For that matter, the model @konklone mentioned wouldn't have to either.

**Comment by mbland** [comment]
Ohhh...makes perfect sense now, thanks @leahbannon. :-)

**Comment by mbland** [comment]
I'll update the trigger to `18f-pages` and the documentation to suit, then re-ping this thread.

**Comment by NoahKunin** [comment]
I just want to say how :smile: I am that all the right things happened without me having to comment on this once. I'll soon be pleasantly out of (this) job.

Also, info on creating redirects on the `github.io` side if someone wants to switch to pure 18F Pages:

https://github.com/jekyll/jekyll-redirect-from

Seems like each individual GitHub Pages owner will have to add the front-matter per the gem.
