### ISSUE TITLE
Seems like the wrong branch is being built

### ISSUE THREAD

**Issue by dhcole** [18F/pages#10]
We have a `18f-pages` branch on Midas, but it looks like the `devel` (default) branch is being built instead. See view-source:https://pages.18f.gov/midas/README.md vs https://raw.githubusercontent.com/18F/midas/18f-pages/README.md

cc @ultrasaurus 

Refs https://github.com/18F/midas/issues/826

**Comment by dhcole** [comment]
Looks like the issue is that previously, the 18f-pages branch was not cloned explicitly, so now it's only doing a `git pull` on the existing branch (devel). 

https://github.com/18F/pages/blob/18f-pages/hookshot.js#L102

@mbland can you just erase the repo for midas on the server to get this back in line?

**Comment by mbland** [comment]
Done.

**Comment by dhcole** [comment]
Thanks @mbland!
