### ISSUE TITLE
Support a staging branch

### ISSUE THREAD

**Issue by maya** [18F/pages#11]
Currently, 18F pages only supports the production branch. This will let us create a different branch we can use for staging.

**Comment by juliasolorzano** [comment]
+1 nice suggestions @maya!

**Comment by mbland** [comment]
So would y'all prefer `pages.18f.gov/staging/`, or `pages-staging.18f.gov`, or some variation thereon? I've got the webhook working; at this point it's a matter of Nginx/DNS configuration.

**Comment by juliasolorzano** [comment]
`pages-staging.18f.gov`

**Comment by mbland** [comment]
`pages-staging.18f.gov` is now operational. Sample: https://pages-staging.18f.gov/guides-template/. Thoughts on authentication? It may be a good idea, actually.

**Comment by juliasolorzano** [comment]
Maybe we could use the same methods as we use with the hub (e.g. myUSA, see screenshot). Seems like that might be the least painless. Thoughts?

![screen shot 2015-06-04 at 3 24 59 pm](https://cloud.githubusercontent.com/assets/955558/7992473/a909188a-0acd-11e5-914e-1402fa8df59b.png)

**Comment by mbland** [comment]
Would you mind if it was the exact same instance?

**Comment by mbland** [comment]
Actually, done.
