### ISSUE TITLE
Support for server-defined configuration

### ISSUE THREAD

**Issue by mbland** [18F/pages#22]
Per the discussion in 18F/pulse#270, I'm considering generating a `_config_18f_pages.yml` or some such on the fly, to define `baseurl:` and `asset_root:` so that authors of 18F Pages sites don't have to.
- Per @konklone's suggestion, `baseurl:` could default to the name of the repo.
- Users can check in their own `_config_18f_pages.yml` with these fields defined, in which case the server will not generate its version.
- Under this scheme, users building and running locally will have the default root at http://localhost:4000/.
- The `asset_root:` configuration variable is specific to the [`guides_style_18f` gem](https://rubygems.org/gems/guides_style_18f) from [18F/guides-style](https://github.com/18F/guides-style), so it will only influence Pages sites using that gem or otherwise electing to make use of that variable. It is used in the gem's templates to have all Pages-based sites load their CSS from https://pages.18f.gov/guides-template by default, so they get CSS updates without having to upgrade the gem. (Layout and shared JavaScript updates still require a manual gem update, but we hope to automate this process.)

Thoughts? Alternatives?

cc: @arowla @afeld @juliaelman @meiqimichelle @msecret

**Comment by konklone** [comment]
:+1: from me - adds no burden to 18F Pages users, they don't even have to know this feature exists.

**Comment by msecret** [comment]
This sounds like a great idea to me.

**Comment by mbland** [comment]
Good, 'cause I'm just about done with it. :-) Just got to get one more test under control, and one more in place.
