### ISSUE TITLE
Log page builds

### ISSUE THREAD

**Issue by adelevie** [18F/pages#4]
One thing that always frustrated me with GitHub Pages was its opaqueness. You'd have no idea if a build actually started, and refreshing the page constantly was the only way to see if it was working. Eventually GitHub added [descriptive email notifications for build failures](https://github.com/blog/1706-descriptive-error-messages-for-failed-github-pages-builds).

I think we should either mimic that email feature or display somewhere the logs and build status for each site on pages.18f.gov.

**Comment by mbland** [comment]
Shouldn't be too hard to do. What do you think about, as a first approximation, creating `https://pages.18f.gov/REPO-NAME/build.log` files?

**Comment by adelevie** [comment]
I think that's a solid idea and should get us most of the way there. I guess anything more robust would require storing build records in a database?

**Comment by mbland** [comment]
I doubt a database'll be required, but I'm almost ready to shoot you a PR for the original idea. ;-)

**Comment by mbland** [comment]
@adelevie Feel free to reopen this if you need a more extensive solution, or more information.
