### ISSUE TITLE
"Accordion" style left navigation (collapsing sub-items) may make it harder to find information

### ISSUE THREAD

**Issue by brittag** [18F/pages#54]
While thinking about guides information architecture, I found myself with a suggestion: can we consider expanding the sidebar navigation "accordions" by default? I looked around the guides and made a quick list of the ones that use nested items in the sidebar: [Testing Cookbook](https://pages.18f.gov/testing-cookbook/), [Before you ship](https://pages.18f.gov/before-you-ship/), [Methods](https://methods.18f.gov/), [Frontend Guides](https://pages.18f.gov/frontend/css-coding-styleguide/), and [18F Guides Template](https://pages.18f.gov/guides-template/).

In 4/5 of these, expanding all the sub-items would produce a list that's still manageably short. As a reader looking at a guide, I like being able to see an overview at a glance - it helps me quickly understand what a guide has to offer. If I'm looking up a specific topic that happens to be covered by a sub-page, seeing all the sub-pages can help me find and get to that page more quickly.

The Methods guide is one guide that has a lot of items in its navigation list, but expanding all the items doesn't feel too overwhelming to me - it helps me understand what the short section titles (Discover, Decide, etc.) mean.

**Comment by mbland** [comment]
@brittag This'll be configurable via the `expand_nav:` flag in `_config.yml` once we merge 18F/guides-style#32 and push a new release of [`guides_style_18f`](https://rubygems.org/gems/guides_style_18f).

**Comment by mbland** [comment]
Although, I'll warn both you and @afeld, do not, _do not_ taunt me to make this configurable on a per-item basis. Don't do it. Please.

Crap, I'm already thinking about it. It'd be super easy. Once 18F/guides-style#32 goes in, I'll whip up another quick and short PR to enable that. Dammit.

**Comment by afeld** [comment]
The fun thing about @mbland is you just ask "hey, can X thing do Y?" and then the next time you check your notifications, there's a pull request waiting for you :heart:
